[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.development]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.development.environment]
  HUGO_VERSION = "0.68.3"

[build.environment]
  TZ = "America/Mexico_City"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

# A basic redirect rule
[[redirects]]
  from = "https://coronavirusin.mx/"
  to = "https://www.datain.mx"
  status = 301
  force = true

# A basic redirect rule
[[redirects]]
  from = "https://www.coronavirusin.mx/"
  to = "https://www.datain.mx"
  status = 301
  force = true  

# A basic redirect rule
[[redirects]]
  from = "https://www.covid19in.mx/"
  to = "https://www.datain.mx"
  status = 301
  force = true  

# A basic redirect rule
[[redirects]]
  from = "https://covid19in.mx/"
  to = "https://www.datain.mx"
  status = 301
  force = true

[[redirects]]
  from = "/data/results/covid-19-resultado-positivos-indre-2020-04-04.pdf"
  to = "https://datos.covid19in.mx/tablas-diarias/positivos/202004/20200404.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/data/results/covid-19-resultado-positivos-indre-2020-04-:day.pdf"
  to = "https://datos.covid19in.mx/tablas-diarias/positivos/202004/202004:day.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/data/results/covid-19-resultado-:type-indre-2020-04-04.pdf"
  to = "https://datos.covid19in.mx/tablas-diarias/:type/202004/20200404.pdf"
  status = 301
  force = true
